"""add_mfa_and_settings

Revision ID: 04c4e905f840
Revises: a1b2c3d4e5f6
Create Date: 2026-06-29 17:16:32.121500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '04c4e905f840'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_settings',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.add_column('auth_users', sa.Column('mfa_enrollment_status', sa.String(), server_default='NOT_STARTED', nullable=False))
    sa.Column('mfa_secret', sa.String(), nullable=True) # unused sa.Column placeholder deleted
    op.add_column('auth_users', sa.Column('mfa_secret', sa.String(), nullable=True))
    op.add_column('auth_users', sa.Column('mfa_enabled_at', sa.DateTime(), nullable=True))
    op.add_column('auth_users', sa.Column('backup_codes', sa.String(), nullable=True))
    op.add_column('auth_users', sa.Column('mfa_remind_after', sa.DateTime(), nullable=True))
    op.add_column('auth_users', sa.Column('mfa_last_reminder', sa.DateTime(), nullable=True))
    op.add_column('auth_users', sa.Column('mfa_reminder_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('auth_users', sa.Column('last_mfa_verification', sa.DateTime(), nullable=True))
    op.alter_column('auth_users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('auth_users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('content_sections', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('finance', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'active'::character varying"))  # type: ignore
    op.alter_column('finance', 'permissions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))  # type: ignore
    op.alter_column('finance', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))  # type: ignore
    op.alter_column('plans', 'payment_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('refunds', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))  # type: ignore
    op.alter_column('refunds', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))  # type: ignore
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('refunds', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))  # type: ignore
    op.alter_column('refunds', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))  # type: ignore
    op.alter_column('plans', 'payment_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('finance', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))  # type: ignore
    op.alter_column('finance', 'permissions',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))  # type: ignore
    op.alter_column('finance', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'active'::character varying"))  # type: ignore
    op.alter_column('content_sections', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('auth_users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('auth_users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('auth_users', 'last_mfa_verification')
    op.drop_column('auth_users', 'mfa_reminder_count')
    op.drop_column('auth_users', 'mfa_last_reminder')
    op.drop_column('auth_users', 'mfa_remind_after')
    op.drop_column('auth_users', 'backup_codes')
    op.drop_column('auth_users', 'mfa_enabled_at')
    op.drop_column('auth_users', 'mfa_secret')
    op.drop_column('auth_users', 'mfa_enrollment_status')
    op.drop_table('system_settings')
    # ### end Alembic commands ###
