"""Add user fields

Revision ID: 3bcd55f4ed1b
Revises: eead13281905
Create Date: 2026-06-17 18:56:31.712585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bcd55f4ed1b'
down_revision: Union[str, None] = 'eead13281905'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('city', sa.String(), nullable=True))
    op.add_column('users', sa.Column('location', sa.String(), nullable=True))
    op.add_column('users', sa.Column('occupation', sa.String(), nullable=True))
    op.add_column('users', sa.Column('govt_id_copy_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('reimbursement', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('gst_number', sa.String(), nullable=True))
    op.add_column('users', sa.Column('org_location', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'org_location')
    op.drop_column('users', 'gst_number')
    op.drop_column('users', 'reimbursement')
    op.drop_column('users', 'govt_id_copy_url')
    op.drop_column('users', 'occupation')
    op.drop_column('users', 'location')
    op.drop_column('users', 'city')
    # ### end Alembic commands ###
