"""Add documents to companies

Revision ID: 7cd8b35ff6f1
Revises: 3e126a9079fd
Create Date: 2026-06-22 11:31:45.196502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cd8b35ff6f1'
down_revision: Union[str, None] = '3e126a9079fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('documents', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'documents')
    # ### end Alembic commands ###
