"""add_biometric_fields

Revision ID: 7d579c1c8ae7
Revises: 2b485155f57b
Create Date: 2026-06-22 15:27:10.636532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d579c1c8ae7'
down_revision: Union[str, None] = '2b485155f57b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('biometric_required', sa.Boolean(), nullable=True))
    op.add_column('companies', sa.Column('biometric_requested', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'biometric_requested')
    op.drop_column('companies', 'biometric_required')
    # ### end Alembic commands ###
