"""decouple_checkins_from_plans_and_add_working_hours

Revision ID: 9594d2e54f82
Revises: 04c4e905f840
Create Date: 2026-06-30 17:47:45.273050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9594d2e54f82'
down_revision: Union[str, None] = '04c4e905f840'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('biometric_sync_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sync_date', sa.Date(), nullable=False),
    sa.Column('started_time', sa.DateTime(), nullable=False),
    sa.Column('completed_time', sa.DateTime(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('initiated_by', sa.String(), nullable=False),
    sa.Column('imported_count', sa.Integer(), nullable=False),
    sa.Column('updated_count', sa.Integer(), nullable=False),
    sa.Column('skipped_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('api_generated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('checkins', sa.Column('working_hours', sa.Float(), nullable=True))
    op.alter_column('checkins', 'plan_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('checkins', 'plan_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('checkins', 'working_hours')
    op.drop_table('biometric_sync_history')
    # ### end Alembic commands ###
