"""Add company and company_admins

Revision ID: beccdc756dc4
Revises: 3bcd55f4ed1b
Create Date: 2026-06-20 15:51:23.844089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'beccdc756dc4'
down_revision: Union[str, None] = '3bcd55f4ed1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('registration_number', sa.String(), nullable=True),
    sa.Column('gst_number', sa.String(), nullable=True),
    sa.Column('industry_type', sa.String(), nullable=True),
    sa.Column('company_email', sa.String(), nullable=False),
    sa.Column('company_phone', sa.String(), nullable=True),
    sa.Column('company_website', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('pincode', sa.String(), nullable=True),
    sa.Column('max_employee_capacity', sa.Integer(), nullable=True),
    sa.Column('seats_purchased', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('company_registration_doc_url', sa.String(), nullable=True),
    sa.Column('gst_cert_doc_url', sa.String(), nullable=True),
    sa.Column('auth_signatory_id_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['auth_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company_admins',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('auth_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('mobile', sa.String(), nullable=True),
    sa.Column('designation', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['auth_id'], ['auth_users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('auth_id')
    )
    op.drop_constraint('checkins_updated_by_fkey', 'checkins', type_='foreignkey')
    op.drop_constraint('checkins_checkin_approved_by_fkey', 'checkins', type_='foreignkey')
    op.create_foreign_key(None, 'checkins', 'auth_users', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'checkins', 'auth_users', ['checkin_approved_by'], ['id'])
    op.drop_constraint('pricing_updated_by_fkey', 'pricing', type_='foreignkey')
    op.create_foreign_key(None, 'pricing', 'auth_users', ['updated_by'], ['id'])
    op.drop_constraint('queries_user_id_fkey', 'queries', type_='foreignkey')
    op.create_foreign_key(None, 'queries', 'auth_users', ['user_id'], ['id'])
    op.drop_constraint('updates_user_id_fkey', 'updates', type_='foreignkey')
    op.create_foreign_key(None, 'updates', 'auth_users', ['user_id'], ['id'])
    op.drop_constraint('usage_logs_user_id_fkey', 'usage_logs', type_='foreignkey')
    op.create_foreign_key(None, 'usage_logs', 'auth_users', ['user_id'], ['id'])
    op.add_column('users', sa.Column('company_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'users', 'companies', ['company_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'company_id')
    op.drop_constraint(None, 'usage_logs', type_='foreignkey')
    op.create_foreign_key('usage_logs_user_id_fkey', 'usage_logs', 'auth_users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'updates', type_='foreignkey')
    op.create_foreign_key('updates_user_id_fkey', 'updates', 'auth_users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'queries', type_='foreignkey')
    op.create_foreign_key('queries_user_id_fkey', 'queries', 'auth_users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'pricing', type_='foreignkey')
    op.create_foreign_key('pricing_updated_by_fkey', 'pricing', 'auth_users', ['updated_by'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'checkins', type_='foreignkey')
    op.drop_constraint(None, 'checkins', type_='foreignkey')
    op.create_foreign_key('checkins_checkin_approved_by_fkey', 'checkins', 'auth_users', ['checkin_approved_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('checkins_updated_by_fkey', 'checkins', 'auth_users', ['updated_by'], ['id'], ondelete='SET NULL')
    op.drop_table('company_admins')
    op.drop_table('companies')
    # ### end Alembic commands ###
