"""add_subscription_columns_to_company

Revision ID: e7bcd702d284
Revises: 6e33b44ae95e
Create Date: 2026-06-27 07:15:02.866964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7bcd702d284'
down_revision: Union[str, None] = '6e33b44ae95e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('checkins_updated_by_fkey', 'checkins', type_='foreignkey')
    op.drop_constraint('checkins_checkin_approved_by_fkey', 'checkins', type_='foreignkey')
    op.create_foreign_key(None, 'checkins', 'auth_users', ['checkin_approved_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'checkins', 'auth_users', ['updated_by'], ['id'], ondelete='SET NULL')
    op.add_column('companies', sa.Column('subscription_status', sa.String(), nullable=False))
    op.add_column('companies', sa.Column('plan_selected_at', sa.DateTime(), nullable=True))
    op.add_column('companies', sa.Column('selected_plan_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'companies', 'pricing_plans', ['selected_plan_id'], ['id'], ondelete='SET NULL')
    op.add_column('invoices', sa.Column('invoice_number', sa.String(), nullable=True))
    op.add_column('invoices', sa.Column('billing_start_date', sa.Date(), nullable=True))
    op.add_column('invoices', sa.Column('billing_end_date', sa.Date(), nullable=True))
    op.add_column('invoices', sa.Column('due_date', sa.Date(), nullable=True))
    op.add_column('invoices', sa.Column('payment_date', sa.DateTime(), nullable=True))
    op.add_column('invoices', sa.Column('notif_generated_sent', sa.Boolean(), nullable=False))
    op.add_column('invoices', sa.Column('notif_reminder_sent', sa.Boolean(), nullable=False))
    op.add_column('invoices', sa.Column('notif_due_sent', sa.Boolean(), nullable=False))
    op.add_column('invoices', sa.Column('notif_overdue_sent', sa.Boolean(), nullable=False))
    op.create_unique_constraint(None, 'invoices', ['invoice_number'])
    op.drop_constraint('pricing_updated_by_fkey', 'pricing', type_='foreignkey')
    op.create_foreign_key(None, 'pricing', 'auth_users', ['updated_by'], ['id'], ondelete='SET NULL')
    op.drop_constraint('queries_user_id_fkey', 'queries', type_='foreignkey')
    op.create_foreign_key(None, 'queries', 'auth_users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('updates_user_id_fkey', 'updates', type_='foreignkey')
    op.create_foreign_key(None, 'updates', 'auth_users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('usage_logs_user_id_fkey', 'usage_logs', type_='foreignkey')
    op.create_foreign_key(None, 'usage_logs', 'auth_users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usage_logs', type_='foreignkey')
    op.create_foreign_key('usage_logs_user_id_fkey', 'usage_logs', 'auth_users', ['user_id'], ['id'])
    op.drop_constraint(None, 'updates', type_='foreignkey')
    op.create_foreign_key('updates_user_id_fkey', 'updates', 'auth_users', ['user_id'], ['id'])
    op.drop_constraint(None, 'queries', type_='foreignkey')
    op.create_foreign_key('queries_user_id_fkey', 'queries', 'auth_users', ['user_id'], ['id'])
    op.drop_constraint(None, 'pricing', type_='foreignkey')
    op.create_foreign_key('pricing_updated_by_fkey', 'pricing', 'auth_users', ['updated_by'], ['id'])
    op.drop_constraint(None, 'invoices', type_='unique')
    op.drop_column('invoices', 'notif_overdue_sent')
    op.drop_column('invoices', 'notif_due_sent')
    op.drop_column('invoices', 'notif_reminder_sent')
    op.drop_column('invoices', 'notif_generated_sent')
    op.drop_column('invoices', 'payment_date')
    op.drop_column('invoices', 'due_date')
    op.drop_column('invoices', 'billing_end_date')
    op.drop_column('invoices', 'billing_start_date')
    op.drop_column('invoices', 'invoice_number')
    op.drop_constraint(None, 'companies', type_='foreignkey')
    op.drop_column('companies', 'selected_plan_id')
    op.drop_column('companies', 'plan_selected_at')
    op.drop_column('companies', 'subscription_status')
    op.drop_constraint(None, 'checkins', type_='foreignkey')
    op.drop_constraint(None, 'checkins', type_='foreignkey')
    op.create_foreign_key('checkins_checkin_approved_by_fkey', 'checkins', 'auth_users', ['checkin_approved_by'], ['id'])
    op.create_foreign_key('checkins_updated_by_fkey', 'checkins', 'auth_users', ['updated_by'], ['id'])
    # ### end Alembic commands ###
