"""add_biometric_required_and_requested

Revision ID: ec229b27a7ef
Revises: 7d579c1c8ae7
Create Date: 2026-06-22 17:24:19.337703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec229b27a7ef'
down_revision: Union[str, None] = '7d579c1c8ae7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
