export enum AuditAction {
  LOGIN = 'LOGIN',
  PAGE_CREATE = 'PAGE_CREATE',
  PAGE_UPDATE = 'PAGE_UPDATE',
  PAGE_DELETE = 'PAGE_DELETE',
  SPACE_CREATE = 'SPACE_CREATE',
  SPACE_UPDATE = 'SPACE_UPDATE',
  APPROVAL_GRANTED = 'APPROVAL_GRANTED',
  APPROVAL_REJECTED = 'APPROVAL_REJECTED',
}

export enum AuditResourceType {
  USER = 'USER',
  PAGE = 'PAGE',
  SPACE = 'SPACE',
}
