export enum AuditAction {
  LOGIN = 'LOGIN',
  PAGE_CREATE = 'PAGE_CREATE',
  PAGE_UPDATE = 'PAGE_UPDATE',
  PAGE_DELETE = 'PAGE_DELETE',
  SPACE_CREATE = 'SPACE_CREATE',
  SPACE_UPDATE = 'SPACE_UPDATE',
  APPROVAL_GRANTED = 'APPROVAL_GRANTED',
  APPROVAL_REJECTED = 'APPROVAL_REJECTED',
  PAGE_SUBMITTED_FOR_REVIEW = 'PAGE_SUBMITTED_FOR_REVIEW',
  PAGE_APPROVED = 'PAGE_APPROVED',
  PAGE_REJECTED = 'PAGE_REJECTED',
  '2FA_ENABLED' = '2FA_ENABLED',
  '2FA_DISABLED' = '2FA_DISABLED',
  '2FA_LOGIN_SUCCESS' = '2FA_LOGIN_SUCCESS',
}

export enum AuditResourceType {
  USER = 'USER',
  PAGE = 'PAGE',
  SPACE = 'SPACE',
}
